/******************************************************************************
 * raytrace.c
 *
 * Copyright (c) 1999 Frank Dellaert
 * All rights reserved
 *****************************************************************************/

#include <math.h>
#include <malloc.h>
#include <string.h>
#include <mex.h>

/******************************************************************************
% raytrace: trace the ray (O,D) and find closes intersection with polygon set
% [polygon,intersection,t] = raytrace(N,d,T,O,D)
%   N - 3*np normals for polygons (generated by normals.m)
%   d - fourth plane coordinate   (generated by normals.m)
%   T - the transformation matrices (generated by polygonT.m)
%   O - origin of the ray
%   D - direction of the ray
% returns:
%   polygon: the index of the closest intersected polygon (0 if none)
%   intersection: the actual intersection point
%   t : the parameter of the intersection point
******************************************************************************/

#define INNER(a,b) ((a)[0]*(b)[0]+(a)[1]*(b)[1]+(a)[2]*(b)[2])

void rayTrace(const mxArray *N,
              const mxArray *d,
              const mxArray *T,
              const mxArray *O,
              const mxArray *D,
              mxArray **polygon,
              mxArray **intersection,
              mxArray **tvalue
              )
  {
  /*
   * plane representation : Np + d = 0
   * ray representation   : r(t) = O + Dt
   * => intersection point: t = - (d + NO) / ND
   */

  int m = mxGetM(N);
  int nrPolygons = mxGetN(N);

  double *normal    = mxGetPr(N);
  double *planeD    = mxGetPr(d);
  double *T34       = mxGetPr(T);
  double *origin    = mxGetPr(O);
  double *direction = mxGetPr(D);

  int i;
  double *best_t, *P, *R;

  *polygon       = mxCreateDoubleMatrix(1, 1, mxREAL);
  *intersection  = mxCreateDoubleMatrix(3, 1, mxREAL);
  *tvalue        = mxCreateDoubleMatrix(1, 1, mxREAL);
  P = mxGetPr(*polygon);
  R = mxGetPr(*intersection);
  best_t = mxGetPr(*tvalue);
  *best_t = -1;

  for(i=0;i<nrPolygons;i++,normal+=3,planeD++,T34+=12)
    {
    double NO = INNER(normal,origin);
    double ND = INNER(normal,direction);
    if (ND!=0) /* if polygon not parallel to ray */
      {
      double t = -(*planeD+NO)/ND;
      if (t>0 && (*best_t<0 || t<*best_t)) /* if intersection on positive side of ray and smaller than best so far */
        {
        /* the actual intersection point */
        double rx = origin[0] + t*direction[0];
        double ry = origin[1] + t*direction[1];
        double rz = origin[2] + t*direction[2];
        /* calculate 2D coordinate within polygon frame */
        double a = T34[0]*rx+T34[3]*ry+T34[6]*rz+T34[ 9];
        double b = T34[1]*rx+T34[4]*ry+T34[7]*rz+T34[10];
        /* if inside polygon, we have a winner */
        if (a>=0 && b>=0 && (a+b)<=1)
          {
          *best_t = t;
			 *P = i+1;
          R[0]=rx;R[1]=ry;R[2]=rz;
          }
        }
      }
    }
  }

/******************************************************************************
 * MATLAB entry
 *****************************************************************************/

void mexFunction(int nargout, mxArray *out[], int nargin, const mxArray	*in[])
  {
  if (nargin!=5 || nargout!=3)
    mexErrMsgTxt("usage: [polygon,intersection,t] = raytrace(N,d,T,O,D)");
  rayTrace(in[0],in[1],in[2],in[3],in[4],&out[0],&out[1],&out[2]);
  }

/******************************************************************************/
